trigger: none
jobs:
  # https://docs.microsoft.com/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema
  # https://docs.microsoft.com/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
  # https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml


  - job: build_pwsh_WinLatest
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: |
        $PSVersionTable
        .\actions_bootstrap.ps1
        Invoke-Build -File $(Build.SourcesDirectory)\src\Javinizer.build.ps1
      displayName: 'Build and Test - Windows pwsh'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/out/testResults.xml'
        testRunTitle: 'pwsh_winLatest'
      # displayName: 'Publish Test Results'
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(Build.SourcesDirectory)\src\Artifacts
        artifact: Javinizer