name: Build and publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_DOCKER: docker.io
  REGISTRY_GITHUB: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            flavor: |
              latest=auto
            tags: |
              type=semver,pattern={{version}}
          - dockerfile: Dockerfile-cli
            flavor: |
              latest=false
            tags: |
              type=raw,value=latest-cli,enable=true
              type=semver,suffix=-cli,pattern={{version}}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY_DOCKER }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY_GITHUB }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.tags }}
          flavor: ${{ matrix.flavor }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
